IMPORTING LIBRARIES

In [1]:
from numpy import *

CREATING ROW AND COLUMN VECTOR AND SHOWING THEIR SHAPE

In [2]:
vector_row = array([[1,-5,3,2,4]])
vector_column = array([[1],[2],[3],[4]])
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


In [5]:
v_row = array([[1,2,3],[4,5,6],[7,8,9]])
v_colunm = array([[9,8],[7,6]])
print(v_row.shape)
print(v_colunm.shape)

(3, 3)
(2, 2)


In [7]:
from numpy.linalg import norm

Transpose of a Vector

In [8]:
new_vector = vector_row
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, inf)
print("L_1 is: %.1f"%norm_1)
print("L_2 is: %.1f"%norm_2)
print("L_inf is: %.1f"%norm_inf)

[[ 1 -5  3  2  4]]
L_1 is: 5.0
L_2 is: 7.4
L_inf is: 15.0


DOT PRODUCT

In [9]:
#FINDING ANGLE BETWEEN TWO VECTORS USING DOT PRODUCT
v = array([[10, 9, 3]])
w = array([[2, 5, 12]])
theta = arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

[[0.97992471]]


CROSS PRODUCT

In [10]:
v = array([[0, 2, 0]])
w = array([[3, 0, 0]])
print(cross(v, w))

[[ 0  0 -6]]


MATRICES

In [15]:
P = array([[1, 7], [2, 3], [5, 0], [7,7]])
Q = array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(P)
print(Q)
print(dot(P, Q))
print(dot(Q, P))

[[1 7]
 [2 3]
 [5 0]
 [7 7]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]
 [21 56 42 35]]
[[36 39]
 [48 41]]


In [17]:
#SQAURE MATRICES

from numpy.linalg import det

M = array([[0,2,1,3], [3,2,8,1], [1,0,0,3], [0,3,2,1]])
print("M :\n",M)
print("Determinant : %.1f"%det(M))
I = eye(4)
print("I :\n",I)
print("M*I :\n", dot(M,I))


M :
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant : -38.0
I :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I :
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


In [19]:
#SINGULAR NON SINGULAR MATRICES

from numpy.linalg import inv
P = array([[0, 1, 0],[0, 0, 0],[1, 0, 1]])
print("Inverse M:\n",inv(M))
print("Det(p) :\n", det(P))

Inverse M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
Det(p) :
 0.0


In [20]:
#CONDITION NUMBER AND RANK

from numpy.linalg import cond, matrix_rank
A = array([[1,1,0],
[0,1,0],
[1,0,1]])

print("Condition number:\n", cond(A))
print("Rank:\n", matrix_rank(A))
y = array([[1], [2], [1]])
A_y = concatenate((A, y), axis = 1)
print("Augmented matrix:\n", A_y)

Condition number:
 4.048917339522305
Rank:
 3
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


SOLVING LINEAR EQUATIONS

In [21]:
A = array([[4,3,5],[-2,-4,5],[8,8,0]])
y = array([2,5,-3])
x = linalg.solve(A,y)
print(x)

[ 0.375 -0.75   0.55 ]
